35thelement/cs4500_sp19_noideainc

- src/main/resources/application.properties
> updated configuration to user DBSCHEMA

- src/main/java/com/example/cs4500_sp19_noideainc/models/Service.java
- src/main/resources/sql/create_services_tables.sql
Please add JPA service repository and insert data in my services table
> T2 service member1

- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceCategory.java
- src/main/resources/sql/create_service_categories_table.sql
Added 2 files, one Java file for service categories and one SQL file for service categories
> Alex branch

- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ServiceRepository.java
- src/main/resources/sql/insert_services.sql
I did the second part of our team2. Could you confirm it, and start to do Service Service?
> T2 service member2

- src/main/java/com/example/cs4500_sp19_noideainc/services/ServiceService.java
Added ServiceService class with the corresponding methods.
> T2 service member 3

- src/main/java/com/example/cs4500_sp19_noideainc/models/QuestionType.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceSpecificQuestion.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ServiceSpecificQuestionRepository.java
Data modeling for service questions.
> Add data model and repository for service questions

- src/main/java/com/example/cs4500_sp19_noideainc/models/Address.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Admin.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Client.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Permission.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Provider.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Review.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Service.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceClientAssociation.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceClientId.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceProviderAssociation.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceProviderId.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/User.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/AddressRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/AdminRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ClientRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ProviderRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ReviewRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ServiceClientAssociationRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ServiceProviderAssociationRepository.java
updated models to fit the agreed upon diagram.
> User model v2

- src/main/java/com/example/cs4500_sp19_noideainc/models/Provider.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceProviderAssociation.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/User.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/ProviderService.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/UserService.java
Don't merge until UserRepository is all set up!
> Modify User and UserService to include relation to Services

- src/main/java/com/example/cs4500_sp19_noideainc/models/FrequentlyAskedAnswer.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/FrequentlyAskedQuestion.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/FrequentlyAskedAnswerRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/FrequentlyAskedQuestionRepository.java
- src/main/resources/sql/create_frequently_asked_answers_table.sql
- src/main/resources/sql/create_frequently_asked_questions_table.sql
I have created FrequentlyAskedAnswer and FrequentlyAskedQuestion classes and repositories. Please help me merge them into the master branch
> Wisdom member1

- src/main/java/com/example/cs4500_sp19_noideainc/models/FrequentlyAskedAnswer.java
The class was lacking in detail so i wanted to clarify what everything means
> Added javadoc/comments etc to all methods / the class

- src/main/java/com/example/cs4500_sp19_noideainc/services/FrequentlyAskedQuestionService.java
- src/main/resources/sql/insert_frequently_asked_questions.sql
- Add CRUD methods for FAQ
- Create FAQ insert queries
> Wisdom FAQ service

- src/main/java/com/example/cs4500_sp19_noideainc/services/FrequentlyAskedAnswerService.java
- src/main/resources/sql/insert_faq_answers.sql
Created faq answer service class, and inserted some data
> Wisdom member2

- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceQuestion.java
- src/main/java/com/example/cs4500_sp19_noideainc/repositories/ServiceQuestionRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/ServiceQuestionService.java
Added ServiceQuestionService, ServiceQuestion and ServiceQuestionRepository
> Added Service Question Interface, restful and model

- src/main/java/com/example/cs4500_sp19_noideainc/services/FAQAnswerService.java
I added the CRUD service back for faq answers, so that we still have those functionalities in the back end
> add CRUD service for faq answers back

- src/main/java/com/example/cs4500_sp19_noideainc/services/FAQService.java
- Add all other CRUDs back to FAQService
> add other cruds back to FAQservice

- src/main/java/com/example/cs4500_sp19_noideainc/services/SearchPredicate.java
I added the search predicate class with Javadoc, a constructor, getters and setters.
> Added class SearchPredicate

- src/main/java/com/example/cs4500_sp19_noideainc/services/ServiceSearch.java
I added the skeleton for service search
> Added ServiceSearch

- src/main/java/com/example/cs4500_sp19_noideainc/models/DeliveryFee.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Estimate.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/Frequency.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ProgressiveSubcharge.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ProgressiveSurcharge.java
- src/test/java/com/example/cs4500_sp19_noideainc/models/DeliveryFeeEstimateTest.java
Please make sure my implementation of estimate fee is correct
> Wisdom estimate fee

- pom.xml
- src/main/java/com/example/cs4500_sp19_noideainc/models/Estimate.java
- src/test/java/com/example/cs4500_sp19_noideainc/models/DeliveryFeeEstimateTest.java
This is the updated algorithm of estimate fee and tests for the flat fee
> Wisdom algorithm

- src/test/java/com/example/cs4500_sp19_noideainc/models/DeliveryFeeEstimateTest.java
- added tests for weekend and holiday frequency (percentage)
> Wisdom holiday weekends

- src/test/java/com/example/cs4500_sp19_noideainc/models/DeliveryFeeEstimateTest.java
- fix some tests (holiday & weekend) to make them clearer
- correct indentation
> Fix weekend holiday

- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceQuestion.java
- src/main/resources/sql/insert_service_question.sql
service question fixes ready to go to master
> Fix JPA enum handling and update insert queries

- src/main/java/com/example/cs4500_sp19_noideainc/repositories/FAQRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/FAQService.java
I added the filtering feature for the FAQ. Could you test it and merge it for me?
> Filtering faq

- src/main/java/com/example/cs4500_sp19_noideainc/repositories/FAQAnswerRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/FAQAnswerService.java
just implemented the code for filtering faq answers
> Filtering faq answers

- src/main/java/com/example/cs4500_sp19_noideainc/repositories/PagedFAQRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/FAQService.java
- Added basic pagination stuff for FAQ (may need to update later as the front end is implemented)
> Wisdom pagination server

- src/test/java/com/example/cs4500_sp19_noideainc/services/FAQServiceTest.java
- added basic test for paged FAQ (exactly 10 faqs)
> Test faqs paged

- src/test/java/com/example/cs4500_sp19_noideainc/services/FAQServiceTest.java
> Filtering faq test

- src/main/java/com/example/cs4500_sp19_noideainc/repositories/PagedServiceAnswerRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/ServiceAnswerService.java
Added backend ServiceAnswer code
> Pagination backend ServiceAnswer

- src/main/java/com/example/cs4500_sp19_noideainc/models/QuestionType.java
- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceQuestion.java
- src/main/java/com/example/cs4500_sp19_noideainc/utils/ServiceSearch.java
- src/test/java/com/example/cs4500_sp19_noideainc/utils/ServiceSearchTest.java
Getting an error with JPA not playing well with enums, it worked locally
but didn't work on the heroku remote. Figured the easiest fix was to
just convert it to a string.
> Convert question type from enum to string

- src/main/java/com/example/cs4500_sp19_noideainc/services/ServiceSearchService.java
- src/main/java/com/example/cs4500_sp19_noideainc/utils/SearchPredicate.java
- src/main/java/com/example/cs4500_sp19_noideainc/utils/ServiceSearch.java
> Service search service

- src/main/java/com/example/cs4500_sp19_noideainc/services/UserAuthenticationService.java
> added register in the service

- src/main/java/com/example/cs4500_sp19_noideainc/repositories/AddressRepository.java
- src/main/java/com/example/cs4500_sp19_noideainc/services/UserService.java
- src/main/resources/sql/insert_addresses.sql
- src/main/resources/sql/insert_users.sql
add a function to get address by user id
> Search bar

- src/main/java/com/example/cs4500_sp19_noideainc/services/UserAuthenticationService.java
- src/test/java/com/example/cs4500_sp19_noideainc/services/UserAuthenticationServiceTest.java
register unit testing is done!
> Register testing

- src/test/java/com/example/cs4500_sp19_noideainc/services/UserServiceTest.java
> unit test for find address by user id

- src/main/java/com/example/cs4500_sp19_noideainc/models/ServiceAnswer.java
Need access to a Service Answer's corresponding Service Question in
order to update provider info on the business service screen.
> Add ServiceQuestion relationship to ServiceAnswer json output

- src/test/java/com/example/cs4500_sp19_noideainc/services/ServiceCategoryTest.java
- src/test/java/com/example/cs4500_sp19_noideainc/services/ServiceServiceTest.java
Tests for service score & categories.
> A9 unit test
